// Troll++ content header.
#define trollar int
#define oilwater float
#define trolltroll double
#define trollornot bool
#define trollpoint *
#define unchangeabletroll const
#define trollge void
#define trolls [
#define notrolls ]
#define troll {
#define trolled }
#define trolling (
#define toomuchtrolling )
#define trollingcomplete return
#define littletrolling <
#define littletrollinglittletrolling <<
#define lotsoftrolling >
#define sametroll ==
#define ortroll ||
#define andtroll &&
#define nottroll !
#define settroll =
#define trolon :
#define semitrolon ;
#define trollspace namespace
#define trollsomeone +
#define trollsomeonetrollsomeone ++
#define trollsomeoneby +=
#define trollexponentially ^
#define trollapercentile %
#define untroll -
#define untrolluntroll --
#define untrollby -=
#define grouptroll *
#define groupuntroll /
#define trollxtimes for
#define trolluntilfalse while
#define atroll class
#define createtroll new
#define trollandshowtoothers public
#define trollandkeeptoseld private
#define notroll nullptr
#define notatroll NULL
#define trollbot auto
#define trollhouse struct
#define blocked ,
#define trolliftrue if
#define otherwise else
#define stoptrolling break
#define skipcurrentvictim continue
#define istrolling true
#define isnottrolling false
#define trolltern ? 